site_name: Introduction to using R on HPC clusters
site_url: https://finnsdottir.github.io/r-clusters-may2026/
theme:
  name: material
  palette:
    primary: blue
  features:
  - navigation.sections
  - navigation.top
  - content.code.copy

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      
nav:
  - Introduction: index.md
  - Introduction to R and RStudio:
    - Using RStudio: basics.md
    - Basic syntax: syntax.md
    - Getting started in RStudio: getting_started.md
  - Analysing data with R:
    - Inspecting data: inspecting.md
    - Wrangling data: wrangling.md
    - Visualizing data: visualizing.md
  - Using R on the clusters:
    - Accessing RStudio: rstudio.md
    - Analysing data in RStudio: analysing_rstudio.md
    - Using R in the shell: rscripts.md
    - Running jobs with R: batch_jobs.md
  

extra_css:
  - stylesheets/extra.css

